spring:
  application:
    name: shortenurl
  redis:
    host: redis
    port: 6379

endpoints:
  metrics:
    sensitive: false
  shutdown:
    enabled: false
  health:
    sensitive: false

management:
  endpoints:
    web:
      exposure:
        include: "*"  #<2>
  endpoint:
    health:
      show-details: ALWAYS